#!/usr/bin/env python3
"""Write the Vulkan entry points the renderer calls, for the Switch build.

usage: gen_vk_switch.py VULKAN_CORE_H RUNTIME_SRC_DIR OUT.cpp

The Switch build links Mesa NVK directly (no Vulkan loader). NVK exposes
nvk_loaderless_GetInstanceProcAddr / GetDeviceProcAddr; this script defines every vk* function
the runtime names as a forwarder that resolves its target once. Deferred public
symbols are owned by vk_record_thread.cpp; this emits their nvk_real_* targets
and synchronizing host-call wrappers instead.
"""
import os
import re
import sys
from pathlib import Path


def deferred_calls(src):
    """The X-macro is also the handwritten wrapper implementation's call list."""
    path = Path(src) / "platform/switch/vk_record_calls.inc"
    text = path.read_text()
    calls = {}
    for m in re.finditer(r"VK_RECORD_CALL\((\w+),\s*(vk\w+),\s*\((.*?)\),", text, re.S):
        ret, name, params = m.groups()
        if name in calls:
            raise ValueError("duplicate deferred entry point: " + name)
        calls[name] = (ret, " ".join(params.split()))
    if not calls:
        raise ValueError("empty deferred Vulkan call list: " + str(path))
    return calls


def synchronizing(name, params):
    # Handles nested in VkWait/SignalSemaphoreInfo are covered explicitly.
    # Output handles count too: create/allocate accesses of these object classes
    # are rare, and draining them keeps this rule conservative for future calls.
    handles = r"\bVk(?:Queue|CommandBuffer|CommandPool|Fence|Semaphore|SwapchainKHR|QueryPool)\b"
    return (bool(re.search(handles, params)) or
            name in {"vkDeviceWaitIdle", "vkWaitSemaphores", "vkSignalSemaphore",
                     "vkGetSemaphoreCounterValue", "vkResetDescriptorPool", "vkUnmapMemory"} or
            name.startswith(("vkDestroy", "vkFree")))


def prototypes(header):
    text = open(header).read()
    out = {}
    for m in re.finditer(r"VKAPI_ATTR\s+([\w\s\*]+?)\s+VKAPI_CALL\s+(vk\w+)\(\s*(.*?)\);", text, re.S):
        ret, name, params = m.group(1).strip(), m.group(2), " ".join(m.group(3).split())
        out[name] = (ret, params)
    return out


def param_names(params):
    if params in ("void", ""):
        return []
    names = []
    for p in params.split(","):
        p = re.sub(r"\[.*?\]", "", p).strip()
        names.append(re.findall(r"\w+", p)[-1])
    return names


def used(src_dir):
    names = set()
    for root, _, files in os.walk(src_dir):
        for f in files:
            if f.endswith((".cpp", ".h", ".c")):
                with open(os.path.join(root, f), errors="replace") as fh:
                    text = fh.read()
                    names.update(re.findall(r"\b(vk[A-Z]\w+)\s*\(", text))
                    names.update(re.findall(r'"(vk[A-Z]\w+)"', text))
    return names


def main(header, src, out_path):
    protos = prototypes(header)
    deferred = deferred_calls(src)
    runtime_names = used(src)
    unknown = sorted(n for n in runtime_names if n.startswith("vkCmd") and n not in deferred)
    if unknown:
        raise ValueError("vkCmd calls lack an owned recording policy: " + ", ".join(unknown))
    for name, signature in deferred.items():
        if protos.get(name) != signature:
            raise ValueError("deferred signature does not match Vulkan header: " + name)
    names = sorted((runtime_names & protos.keys()) | deferred.keys())
    special = {"vkGetInstanceProcAddr", "vkGetDeviceProcAddr", "vkCreateInstance"}
    lines = [
        "// Generated by tools/switch/gen_vk_switch.py: Vulkan entry points forwarded to Mesa NVK (no loader).",
        "#include <vulkan/vulkan.h>",
        '#include "platform/switch/vk_record_thread.h"',
        "#include <cstdio>",
        "#include <cstdlib>",
        "#include <cstring>",
        "",
        'extern "C" {',
        "VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL nvk_loaderless_GetInstanceProcAddr(VkInstance, const char*);",
        "VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL nvk_loaderless_GetDeviceProcAddr(VkDevice, const char*);",
        "}",
        "",
        "static VkInstance g_instance = VK_NULL_HANDLE;",
        "static PFN_vkVoidFunction resolve(const char* name) {",
        "    PFN_vkVoidFunction f = g_instance ? nvk_loaderless_GetInstanceProcAddr(g_instance, name) : nullptr;",
        "    return f ? f : nvk_loaderless_GetInstanceProcAddr(VK_NULL_HANDLE, name);",
        "}",
        "",
        "static PFN_vkVoidFunction wrapped(const char* name) {",
    ]
    for n in names:
        if n in deferred or synchronizing(n, protos[n][1]):
            lines.append('    if (!std::strcmp(name, "%s")) return (PFN_vkVoidFunction)&%s;' % (n, n))
    lines += [
        '    if (!std::strncmp(name, "vkCmd", 5)) vkrecord::unsupported("unwrapped vkCmd proc lookup");',
        "    return nullptr;",
        "}",
        "",
        'extern "C" {',
        "VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL vkGetInstanceProcAddr(VkInstance instance, const char* pName) {",
        "    if (auto f = wrapped(pName)) return f;",
        "    return nvk_loaderless_GetInstanceProcAddr(instance, pName);",
        "}",
        "VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL vkGetDeviceProcAddr(VkDevice device, const char* pName) {",
        "    if (auto f = wrapped(pName)) return f;",
        "    return nvk_loaderless_GetDeviceProcAddr(device, pName);",
        "}",
        "VKAPI_ATTR VkResult VKAPI_CALL vkCreateInstance(const VkInstanceCreateInfo* pCreateInfo,",
        "                                                const VkAllocationCallbacks* pAllocator, VkInstance* pInstance) {",
        '    auto fn = (PFN_vkCreateInstance)nvk_loaderless_GetInstanceProcAddr(VK_NULL_HANDLE, "vkCreateInstance");',
        "    VkResult r = fn(pCreateInfo, pAllocator, pInstance);",
        "    if (r == VK_SUCCESS) g_instance = *pInstance;",
        "    return r;",
        "}",
    ]
    for n in names:
        if n in special:
            continue
        ret, params = protos[n]
        args = ", ".join(param_names(params))
        public = "nvk_real_" + n if n in deferred else n
        lines.append("VKAPI_ATTR %s VKAPI_CALL %s(%s) {" % (ret, public, params))
        if n not in deferred and synchronizing(n, params):
            if ret == "VkResult":
                lines.append("    if (VkResult r = vkrecord::drain(); r != VK_SUCCESS) return r;")
            else:
                lines.append("    (void)vkrecord::drain();")
        lines.append('    static PFN_%s fn = (PFN_%s)resolve("%s");' % (n, n, n))
        lines.append("    %sfn(%s);" % ("" if ret == "void" else "return ", args))
        lines.append("}")
    lines.append("}")
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("%d Vulkan entry points" % len(set(names) | special))


if __name__ == "__main__":
    main(*sys.argv[1:4])
